# register
GET http://localhost:5000/api/register
Content-Type: application/json
{
    name: "Pham Minh Duy",
    email: "duy.pham@gmail.com",
    phoneNum: "1234567890",
    gender: "male",
    studentId: "1919191",
    password: "duyduy",
    image: "http://"
}
###
# log in

GET http://localhost:5000/api/login
Content-Type: application/json
{
    email: "duypm1111",
    password: "aaaaaa"
}

###
# get list of item
# filter gồm có page, limit, author, category, name, sortby, status, markby
# xong
GET http://localhost:5000/api/items?page=1&limit=10
{
    token: "" 
}
### có thể không có token (nếu chưa đăng nhập)
###
GET http://localhost:5000/api/items?author=author_id_here

###
GET http://localhost:5000/api/items?category=giaotrinh

###
GET http://localhost:5000/api/items?name=giaitich1

###
GET http://localhost:5000/api/items?markby=user_id_here


# kiểu trả về là danh sách các item
{
    items: [
        {
            _id: "",
            category: "",
            status: "",
            price: "",
            title: "",
            image: "",
            date: "",
            isMarked: "",
            isSelling: "",
            idAuthor: "",
            authorName: "",
            authorImage: "",
        }
    ]
}

### chi tiết mặt hàng
# xong
GET http://localhost:5000/api/item/:itemId
{
    token: "" 
}

### có thể không có token (nếu chưa đăng nhập)
### kiểu trả về
{
    id: "",
    category: "",
    status: "",
    price: 100000,
    title: "",
    description: "",
    address: "",
    numConcerner: 10,
    image: "",
    date: "",
    isMarked: "",
    isSelling: "",
    idAuthor: "",
    authorName: "",
    authorImage: "",
}

### đăng mặt hàng mới
# xong
POST  http://localhost:5000/api/item
Content-Type: application/json
Authorization: token_here
{
    category: "",
    status: "",
    price: 100000,
    title: "",
    description: "",
    image: "",
}

### update mặt hàng
PUT http://localhost:5000/api/item/:itemId
Content-Type: application/json
Authorization: token_here
{
    category: "",
    status: "",
    price: 100000,
    title: "",
    description: "",
    address: "",
    image: "",
    isSelling: ""
}

### xóa mặt hàng
DELETE http://localhost:5000/api/item/:itemId

### đánh dấu mặt hàng
POST http://localhost:5000/api/item/:itemId/mark
Content-Type: application/json
Authorization: token_here

### bỏ đánh dấu mặt hàng
POST http://localhost:5000/api/item/:itemId/mark
Content-Type: application/json
Authorization: token_here

### search saler
# xong
GET http://localhost:5000/api/users?name=duy&sortby=1

### kiểu trả về
{
    users: [
        {
            id: "",
            image: "",
            name: "",
            description: "",
            numSellingItem: 10,
            numSaledItem: 10,
            rate: "",
            numFeedback: 15
        },
    ]
}

### get saler detail
# xong
GET http://localhost:5000/api/user/:userId
### kiểu trả về
{
    id: "",
    image: "",
    name: "",
    description: "",
    numSellingItem: 10,
    numSaledItem: 10,
    rate: "",
    numFeedback: 15,
}

### change user info
# xong
PUT http://localhost:5000/api/user/:userId
Authorization: "token here"

{
    user: {

    }
}
### get saler feedback
# xong
GET http://localhost:5000/api/user/:userId/feedback
### kiểu trả về
{
    feedback: [
        {
            authorId: "",
            authorImage: "",
            authorName: "",
            content: "",
            numStarsRate: 4,
            isDeleted: false,
            createAt: ""
        }
    ]
}
### thêm feedback
# xong
POST http://localhost:5000/api/user/:userId/feedback
Authorization: 
{
    feedback: "",
    numStarsRate: 5
}

### Xóa feedback
# xong
DELETE  http://localhost:5000/api/user/:userId/feedback/:feedbackId