# register
POST http://localhost:5000/api/register
Content-Type: application/json

{
    "name": "Pham Minh Duy",
    "email": "duy1111@gmail.com",
    "phoneNum": "0234567898",
    "gender": "male",
    "password": "duyduy",
    "image": "http://"
}
###
# log in

POST http://localhost:5000/api/login
Content-Type: application/json

{
    "email": "duy111@gmail.com",
    "password": "duyduy"
}

###
# get list of item
# filter gồm có page, limit, author, category, name, sortby, status, markby
# xong
GET http://localhost:5000/api/items?page=1&limit=5

### có thể không có token (nếu chưa đăng nhập)
###
GET http://localhost:5000/api/items?author=6388ed02c7716a285cfdfc59

###
GET http://localhost:5000/api/items?category=book

###
GET http://localhost:5000/api/items?name=Giải tích

###
GET http://localhost:5000/api/items?markby=user_id_here


# kiểu trả về là danh sách các item
{
    items: [
        {
            _id: "",
            category: "",
            status: "",
            price: "",
            title: "",
            image: "",
            date: "",
            isMarked: "",
            isSelling: "",
            idAuthor: "",
            authorName: "",
            authorImage: "",
        }
    ]
}

### chi tiết mặt hàng
# xong
GET http://localhost:5000/api/item/63890a8196d966305c73a641


### có thể không có token (nếu chưa đăng nhập)
### kiểu trả về
{
    id: "",
    category: "",
    status: "",
    price: 100000,
    title: "",
    description: "",
    address: "",
    numConcerner: 10,
    image: "",
    date: "",
    isMarked: "",
    isSelling: "",
    idAuthor: "",
    authorName: "",
    authorImage: "",
}

### đăng mặt hàng mới
# xong
POST http://localhost:5000/api/item
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiNjM4OGVjM2EyYmRhZTMxMjc4M2JlNjEyIiwiZW1haWwiOiJkdXkucGhhbUBnbWFpbC5jb20iLCJpYXQiOjE2Njk5MjM5NDksImV4cCI6MTY2OTkzMTE0OX0.Fc7W4RYLUSg1vdpmY_IBoECPmNy4k6Aa_4ixjgB1Npc

{
    "category": "electronics",
    "status": "used",
    "price": 5000000,
    "title": "Điện thoại 3",
    "description": "Mô tả 3",
    "image": "http://vanhoanghethuat.vn/datasite///201807/BAI_VIET_14562/03%20(3).jpg"
}

### update mặt hàng
PUT http://localhost:5000/api/item/63890b3596d966305c73a65f
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiNjM4OGVjM2EyYmRhZTMxMjc4M2JlNjEyIiwiZW1haWwiOiJkdXkucGhhbUBnbWFpbC5jb20iLCJpYXQiOjE2Njk5MjM5NDksImV4cCI6MTY2OTkzMTE0OX0.Fc7W4RYLUSg1vdpmY_IBoECPmNy4k6Aa_4ixjgB1Npc

{
    "category": "book",
    "status": "used",
    "price": 100000,
    "isSelling": false
}

### xóa mặt hàng
DELETE http://localhost:5000/api/item/63890b3596d966305c73a65f
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiNjM4OGVjM2EyYmRhZTMxMjc4M2JlNjEyIiwiZW1haWwiOiJkdXkucGhhbUBnbWFpbC5jb20iLCJpYXQiOjE2Njk5MjM5NDksImV4cCI6MTY2OTkzMTE0OX0.Fc7W4RYLUSg1vdpmY_IBoECPmNy4k6Aa_4ixjgB1Npc

### đánh dấu mặt hàng
POST http://localhost:5000/api/item/63890a8196d966305c73a641/mark
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiNjM4OGVjM2EyYmRhZTMxMjc4M2JlNjEyIiwiZW1haWwiOiJkdXkucGhhbUBnbWFpbC5jb20iLCJpYXQiOjE2Njk5MjM5NDksImV4cCI6MTY2OTkzMTE0OX0.Fc7W4RYLUSg1vdpmY_IBoECPmNy4k6Aa_4ixjgB1Npc

### bỏ đánh dấu mặt hàng
DELETE  http://localhost:5000/api/item/63890a8196d966305c73a641/mark
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiNjM4OGVjM2EyYmRhZTMxMjc4M2JlNjEyIiwiZW1haWwiOiJkdXkucGhhbUBnbWFpbC5jb20iLCJpYXQiOjE2Njk5MjM5NDksImV4cCI6MTY2OTkzMTE0OX0.Fc7W4RYLUSg1vdpmY_IBoECPmNy4k6Aa_4ixjgB1Npc

### search saler
# xong
GET http://localhost:5000/api/users?name=duy&sortby=rate

### kiểu trả về
{
    users: [
        {
            id: "",
            image: "",
            name: "",
            description: "",
            numSellingItem: 10,
            numSaledItem: 10,
            rate: "",
            numFeedback: 15
        },
    ]
}

### get saler detail
# xong
GET http://localhost:5000/api/user/6388ec3a2bdae312783be612
### kiểu trả về
{
    id: "",
    image: "",
    name: "",
    description: "",
    numSellingItem: 10,
    numSaledItem: 10,
    rate: "",
    numFeedback: 15,
}

### change user info
# xong
PUT http://localhost:5000/api/user/6388ec3a2bdae312783be612
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiNjM4OGVjM2EyYmRhZTMxMjc4M2JlNjEyIiwiZW1haWwiOiJkdXkucGhhbUBnbWFpbC5jb20iLCJpYXQiOjE2Njk5MjM5NDksImV4cCI6MTY2OTkzMTE0OX0.Fc7W4RYLUSg1vdpmY_IBoECPmNy4k6Aa_4ixjgB1Npc

{
    "user": {
        "name": "duy after update"
    }
}
### get saler feedback
# xong
GET http://localhost:5000/api/user/637f275fa8e8180e88b8f1a8/feedback
### kiểu trả về
{
    feedback: [
        {
            authorId: "",
            authorImage: "",
            authorName: "",
            content: "",
            numStarsRate: 4,
            isDeleted: false,
            createAt: ""
        }
    ]
}
### thêm feedback
# xong
POST http://localhost:5000/api/user/637f275fa8e8180e88b8f1a8/feedback
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiNjM4OGVjM2EyYmRhZTMxMjc4M2JlNjEyIiwiZW1haWwiOiJkdXkucGhhbUBnbWFpbC5jb20iLCJpYXQiOjE2Njk5MjM5NDksImV4cCI6MTY2OTkzMTE0OX0.Fc7W4RYLUSg1vdpmY_IBoECPmNy4k6Aa_4ixjgB1Npc

{
    "feedback": "Feedback 3",
    "numStarsRate": 2
}

### Xóa feedback
# xong
DELETE  http://localhost:5000/api/user/637f275fa8e8180e88b8f1a8/feedback/638907c55e5594284887a61d
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiNjM4OGVjM2EyYmRhZTMxMjc4M2JlNjEyIiwiZW1haWwiOiJkdXkucGhhbUBnbWFpbC5jb20iLCJpYXQiOjE2Njk5MjM5NDksImV4cCI6MTY2OTkzMTE0OX0.Fc7W4RYLUSg1vdpmY_IBoECPmNy4k6Aa_4ixjgB1Npc
